### ISSUE TITLE
Need Help.. similar controller model 

### ISSUE THREAD

**Issue by zenio7** [olivluca/beauty-r1-android-interceptor#2]
Hello. I'm newbie in C lang.
I want to modify code for my new remotecontroller
(It has named Beauty-R1, but little different.
like this
---
Watching:: /dev/input/
The file event5 was Created with WD 1
Device /dev/input/event5 name Beauty-R1 Consumer Control
The file event6 was Created with WD 1
Device /dev/input/event6 name Beauty-R1 Mouse
---
I modified
    if (strcmp("Beauty-R1",name)==0) {
to 
    if (strcmp("Beauty-R1 Mouse",name)==0) {

But debug mode print this message and do nothing. 
(if I press down button)
ts 1725042501.    158084 type 2 code 0 value -2047
ts 1725042501.    158084 type 2 code 1 value 2047
ts 1725042501.    158084 type 0 code 0 value 0
ts 1725042501.    167338 type 2 code 0 value 160
ts 1725042501.    167338 type 2 code 1 value -381
ts 1725042501.    167338 type 0 code 0 value 0
ts 1725042501.    265346 type 2 code 0 value -2047
ts 1725042501.    265346 type 2 code 1 value 2047
ts 1725042501.    265346 type 0 code 0 value 0
ts 1725042501.    297912 type 2 code 0 value 160
ts 1725042501.    297912 type 2 code 1 value -221
ts 1725042501.    297912 type 0 code 0 value 0
ts 1725042501.    331503 type 4 code 4 value 589825
ts 1725042501.    331503 type 1 code 272 value 1
ts 1725042501.    331503 type 0 code 0 value 0
ts 1725042501.    364641 type 2 code 0 value 2
ts 1725042501.    364641 type 2 code 1 value -3
ts 1725042501.    364641 type 0 code 0 value 0
ts 1725042501.    397312 type 2 code 1 value -50
ts 1725042501.    397312 type 0 code 0 value 0
ts 1725042501.    427957 type 2 code 1 value -50
ts 1725042501.    427957 type 0 code 0 value 0
ts 1725042501.    460347 type 2 code 1 value -50
ts 1725042501.    460347 type 0 code 0 value 0
ts 1725042501.    493157 type 2 code 1 value -50
ts 1725042501.    493157 type 0 code 0 value 0
ts 1725042501.    526998 type 4 code 4 value 589825
ts 1725042501.    526998 type 1 code 272 value 0
ts 1725042501.    526998 type 0 code 0 value 0
ts 1725042501.    557870 type 2 code 0 value -2047
ts 1725042501.    557870 type 2 code 1 value 2047
ts 1725042501.    557870 type 0 code 0 value 0
ts 1725042501.    590480 type 2 code 0 value 160
ts 1725042501.    590480 type 2 code 1 value -221
ts 1725042501.    590480 type 0 code 0 value 0

(Up button pressed)
ts 1725042624.    283445 type 2 code 0 value -2047
ts 1725042624.    283445 type 2 code 1 value 2047
ts 1725042624.    283445 type 0 code 0 value 0
ts 1725042624.    314793 type 2 code 0 value 160
ts 1725042624.    314793 type 2 code 1 value -541
ts 1725042624.    314793 type 0 code 0 value 0
ts 1725042624.    378285 type 4 code 4 value 589825
ts 1725042624.    378285 type 1 code 272 value 1
ts 1725042624.    378285 type 0 code 0 value 0
ts 1725042624.    412295 type 2 code 1 value 80
ts 1725042624.    412295 type 0 code 0 value 0
ts 1725042624.    442850 type 2 code 1 value 80
ts 1725042624.    442850 type 0 code 0 value 0
ts 1725042624.    474930 type 2 code 1 value 80
ts 1725042624.    474930 type 0 code 0 value 0
ts 1725042624.    508694 type 2 code 1 value 80
ts 1725042624.    508694 type 0 code 0 value 0
ts 1725042624.    540286 type 4 code 4 value 589825
ts 1725042624.    540286 type 1 code 272 value 0
ts 1725042624.    540286 type 0 code 0 value 0
ts 1725042624.    572956 type 2 code 0 value -2047
ts 1725042624.    572956 type 2 code 1 value 2047
ts 1725042624.    572956 type 0 code 0 value 0
ts 1725042624.    605735 type 2 code 0 value 160
ts 1725042624.    605735 type 2 code 1 value -541
ts 1725042624.    605735 type 0 code 0 value 0

(if I pressed OK button-Middle of arrow buttons)
ts 1725042545.    664611 type 2 code 0 value -2047
ts 1725042545.    664611 type 2 code 1 value 2047
ts 1725042545.    664611 type 0 code 0 value 0
ts 1725042545.    696675 type 2 code 0 value 160
ts 1725042545.    696675 type 2 code 1 value -381
ts 1725042545.    696675 type 0 code 0 value 0
ts 1725042545.    794483 type 4 code 4 value 589825
ts 1725042545.    794483 type 1 code 272 value 1
ts 1725042545.    794483 type 0 code 0 value 0
ts 1725042545.    827022 type 4 code 4 value 589825
ts 1725042545.    827022 type 1 code 272 value 0
ts 1725042545.    827022 type 0 code 0 value 0

How do I modify work well?

**Comment by olivluca** [comment]
Well, it's not simple, you'll have to observe the sequence of events (type/code/value) and devise a strategy to turn that into keypresses.
See, e.g.  https://www.kernel.org/doc/html/latest/input/event-codes.html and https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input-event-codes.h

**Comment by zenio7** [comment]
Thanks for your reply. I saw the documents and decide to return :)
